### ISSUE TITLE
tim.h file

### ISSUE THREAD

**Issue by maygut** [esden/libstm32#1]
Hi,
I am trying to use the tim.h file for my project using an stm32f401 microcontroller. When I try to compile it keeps getting the error that it can not find <cmsis/stm32.h> a library needed for tim.h. I was wondering if you knew where i could download cmsis/stm32.h file?

**Comment by esden** [comment]
Hi... and wow! You dug out an ancient project of mine. It even says in the description "Legacy firmware library for stm32. DO NOT USE!!!" You should check out libopencm3 instead https://github.com/libopencm3/libopencm3/

Thanks for reminding me to archive this repository. Noone should be trying to use this. :)
